name: Build and Package Fixtures

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: 'fixtures'
            evm-type: 'main'
            fill-params: ''
            solc: '0.8.21'
            python: '3.11'
          - name: 'fixtures_develop'
            evm-type: 'develop'
            fill-params: '--until=Cancun'
            solc: '0.8.21'
            python: '3.11'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/build-evm
        id: evm-builder
        with:
          type: ${{ matrix.evm-type }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install solc compiler
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then PLATFORM="linux-amd64"; else PLATFORM="macosx-amd64"; fi
          RELEASE_NAME=$(curl https://binaries.soliditylang.org/${PLATFORM}/list.json | jq -r --arg SOLC_VERSION "${{ matrix.solc }}" '.releases[$SOLC_VERSION]')
          wget -O $GITHUB_WORKSPACE/bin/solc https://binaries.soliditylang.org/${PLATFORM}/$RELEASE_NAME
          chmod a+x $GITHUB_WORKSPACE/bin/solc
          echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH
      - name: Run fixtures fill and create fixtures tree hash file
        shell: bash
        run: |
          pip install --upgrade pip
          python -m venv env
          source env/bin/activate
          pip install -e .
          fill ${{ matrix.fill-params }}
          dfx --generate-fixtures-tree-only
          mv fixtures_tree.json ${{ matrix.name }}_tree.json
      - name: Create fixtures info file
        shell: bash
        run: |
          echo -e "ref: $GITHUB_REF \ncommit: $GITHUB_SHA\nbuild: $(date +"%Y-%m-%dT%H:%M:%SZ")" \
          > fixtures/info.txt
      - name: Create fixtures tree hash file
        shell: bash
        run: |
          dfx --generate-fixtures-tree-only
          mv fixtures_tree.json ${{ matrix.name }}_tree.json
      - name: Upload fixtures tree hash file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}-tree-hash
          path: ${{ matrix.name }}_tree.json
      - name: Tar fixtures output
        shell: bash
        run: |
          tar -czvf ${{ matrix.name }}.tar.gz ./fixtures
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}-artifacts
          path: |
            ${{ matrix.name }}.tar.gz
            ${{ matrix.name }}_tree.json
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: .
      - name: Draft Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            fixtures.tar.gz
            fixtures_develop.tar.gz
          draft: true
          generate_release_notes: true
          fail_on_unmatched_files: true