name: Build and Package Fixtures for a feature

on:
  push:
    tags:
      - '*@v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Get feature name
        id: feature-name
        shell: bash
        run: |
          echo name=${GITHUB_REF_NAME//@*/} >> "$GITHUB_OUTPUT"
      - uses: ./.github/actions/build-fixtures
        with:
          name: ${{ steps.feature-name.outputs.name }}
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
      - name: Draft Pre-release
        uses: softprops/action-gh-release@v2
        with:
          files: './**'
          draft: true
          prerelease: true
          generate_release_notes: true
          fail_on_unmatched_files: true