name: Run Tox Verifications

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: '3.10'
            solc: '0.8.20'
            evm-type: 'main'
            tox-cmd: 'tox run-parallel --parallel-no-spinner'
          - os: ubuntu-latest
            python: '3.12'
            solc: '0.8.23'
            evm-type: 'main'
            tox-cmd: 'tox run-parallel --parallel-no-spinner'
          - os: ubuntu-latest
            python: '3.11'
            solc: '0.8.21'
            evm-type: 'main'  # 'develop'
            tox-cmd: 'tox run-parallel --parallel-no-spinner'  # 'tox -e tests-develop'
          - os: macos-latest
            python: '3.11'
            solc: '0.8.22'
            evm-type: 'main'
            tox-cmd: 'tox run-parallel --parallel-no-spinner'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/build-evm
        id: evm-builder
        with:
          type: ${{ matrix.evm-type }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
      - name: Install solc compiler
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then PLATFORM="linux-amd64"; else PLATFORM="macosx-amd64"; fi
          RELEASE_NAME=$(curl https://binaries.soliditylang.org/${PLATFORM}/list.json | jq -r --arg SOLC_VERSION "${{ matrix.solc }}" '.releases[$SOLC_VERSION]')
          wget -O $GITHUB_WORKSPACE/bin/solc https://binaries.soliditylang.org/${PLATFORM}/$RELEASE_NAME
          chmod a+x $GITHUB_WORKSPACE/bin/solc
          echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH
      - name: Setup Tools/Dependencies Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && sudo apt-get install -y aspell aspell-en
      - name: Setup Tools/Dependencies macOS
        if: runner.os == 'macOS'
        run: |
          brew install aspell
          # Add additional packages on 3.11: https://github.com/ethereum/execution-spec-tests/issues/274
          if [ ${{ matrix.python }} == '3.11' ]; then brew install autoconf automake libtool; fi
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox (CPython)
        run: ${{ matrix.tox-cmd }}
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            README.md
            docs/**/*.md
